name: Release Workflow
on:
  release:
    types: [published]

jobs:
  release:
    env:
      REF: ${{ github.ref }}
    name: Release Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          docker build \
            -t ghcr.io/leakytap/wait-for-it-docker:${REF##*/} \
            -t ghcr.io/leakytap/wait-for-it-docker:latest .

      - name: Push
        run: |
          docker login ghcr.io -u Jesse0Michael -p ${{ secrets.PAT }}
          docker push ghcr.io/leakytap/wait-for-it-docker:${REF##*/}
          docker push ghcr.io/leakytap/wait-for-it-docker:latest
